export const AUDIT_ACTIONS = {
  // Auth
  LOGIN: 'LOGIN',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOGOUT: 'LOGOUT',
  TOKEN_REFRESH: 'TOKEN_REFRESH',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',

  // User
  USER_CREATED: 'USER_CREATED',
  USER_UPDATED: 'USER_UPDATED',
  USER_DEACTIVATED: 'USER_DEACTIVATED',
  USER_ACTIVATED: 'USER_ACTIVATED',
  ROLE_ASSIGNED: 'ROLE_ASSIGNED',
  ROLE_REMOVED: 'ROLE_REMOVED',

  // Election
  ELECTION_CREATED: 'ELECTION_CREATED',
  ELECTION_UPDATED: 'ELECTION_UPDATED',
  ELECTION_STATUS_CHANGED: 'ELECTION_STATUS_CHANGED',
  ELECTION_CANCELLED: 'ELECTION_CANCELLED',
  NOMINATION_OPENED: 'NOMINATION_OPENED',
  NOMINATION_CLOSED: 'NOMINATION_CLOSED',
  VOTING_STARTED: 'VOTING_STARTED',
  VOTING_CLOSED: 'VOTING_CLOSED',
  RESULT_PUBLISHED: 'RESULT_PUBLISHED',

  // Position
  POSITION_CREATED: 'POSITION_CREATED',
  POSITION_UPDATED: 'POSITION_UPDATED',
  POSITION_DELETED: 'POSITION_DELETED',

  // Candidate
  CANDIDATE_SUBMITTED: 'CANDIDATE_SUBMITTED',
  CANDIDATE_APPROVED: 'CANDIDATE_APPROVED',
  CANDIDATE_REJECTED: 'CANDIDATE_REJECTED',
  CANDIDATE_WITHDRAWN: 'CANDIDATE_WITHDRAWN',
  CANDIDATE_DISQUALIFIED: 'CANDIDATE_DISQUALIFIED',

  // Voter
  VOTER_ADDED: 'VOTER_ADDED',
  VOTER_IMPORTED: 'VOTER_IMPORTED',
  VOTER_REMOVED: 'VOTER_REMOVED',

  // Voting
  VOTE_CAST: 'VOTE_CAST',
  DUPLICATE_VOTE_ATTEMPT: 'DUPLICATE_VOTE_ATTEMPT',

  // Result
  RESULT_GENERATED: 'RESULT_GENERATED',
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];
